### ISSUE TITLE
Not returning a snowflake?

### ISSUE THREAD

**Issue by ghostdevv** [utkarsh-pro/nodejs-snowflake#18]
I updated to version 2 from 1 and in my testing I am not getting a snowflake, see the code I am testing with:
```ts
import { Snowflake } from "nodejs-snowflake";

const uid = new Snowflake();

console.log(
    uid.getUniqueID().toString(),
)
```

This yields an id such as `4101121`

**Comment by tangledbytes** [comment]
Hi @ghostdevv, can you try the following which should restore the previous behaviour:
```diff
- const uid = new Snowflake();
+ const uid = new Snowflake({
+    custom_epoch: 1546300800000 // Default epoch < v2
+});
```

From version 2, the default epoch is `Date.now()` and that's why the IDs are smaller in size because the epoch is smaller (hence lesser bits filled). This change was made because `Snowflake` can generate ids that can fit inside 64 bits, so to ensure that the new users aren't starting with a huge ID (because of the 2019 epoch) and hence should be able to use the package for a longer period of time (albeit this period would be 60+ years - mathematically).

I apologize as this should change should have been documented somewhere but wasn't.

**Comment by ghostdevv** [comment]
Ah makes sense, I am used to a snowflake being 18 digits long so it threw me off. I do need the 18 digits as all ids I generate need to be the same shape so will try that!

**Comment by tangledbytes** [comment]
@ghostdevv feel free to reopen the issue in case your issue isn't resolved yet.
